#!/bin/bash

roslaunch so_dso_place_recognition t1.launch
roslaunch so_dso_place_recognition t2.launch
roslaunch so_dso_place_recognition t3.launch
roslaunch so_dso_place_recognition t4.launch
roslaunch so_dso_place_recognition t5.launch
roslaunch so_dso_place_recognition t6.launch
roslaunch so_dso_place_recognition t7.launch
roslaunch so_dso_place_recognition t8.launch
roslaunch so_dso_place_recognition t9.launch
roslaunch so_dso_place_recognition t10.launch
